name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Hugging Face CLI
        run: pip install huggingface-cli
      - name: Configure Hugging Face CLI
        run: huggingface-cli login
          env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
      - name: Push to hub
        run: |
          huggingface-cli repo create Books-Recommendation
          cd Books-Recommendation
          git remote add hf https://SaniyaBubere:$HF_TOKEN@huggingface.co/spaces/SaniyaBubere/Books-Recommendation
          git push hf main
          cd ..
          rm -rf Books-Recommendation
          env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
            MODEL_NAME: Books-Recommendation
